INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Dostoevsky','Idiot',350);
INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Dostoevsky','Crime and Punishment',1500);
INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Tolstoy','Karamazovs brothers',350);
INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Tolstoy','War and Peace',453);
INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Tolstoy','Anna Karenina',537);
INSERT INTO BOOKS(AUTHOR,TITLE,SIZE) VALUES ('Pushkin','Eugeny Onegin',923);